import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Recipe } from 'src/models/recipe';
import { RecipeType } from "src/models/recipe-type";

@Component({
  selector: 'app-folder',
  templateUrl: './folder.page.html',
  styleUrls: ['./folder.page.scss'],
})
export class FolderPage implements OnInit {
  public folder: string;
  public recipes: Recipe[] = [
    { id: 1, title: "Breakfast nr 1", servings: 2, time: 15, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "../../assets/breakfast1.jpg", recipeType: RecipeType[0] },
    { id: 2, title: "Breakfast nr 2", servings: 2, time: 10, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "../../assets/breakfast2.jpg", recipeType: RecipeType[0] },
    { id: 3, title: "Breakfast nr 3", servings: 2, time: 30, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "../../assets/breakfast3.jpg", recipeType: RecipeType[0] },
    { id: 4, title: "Breakfast nr 4", servings: 2, time: 15, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "../../assets/breakfast4.jpg", recipeType: RecipeType[0] },
    { id: 5, title: "Breakfast nr 5", servings: 2, time: 15, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "../../assets/breakfast5.jpg", recipeType: RecipeType[0] },
    { id: 6, title: "Breakfast nr 6", servings: 2, time: 20, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "../../assets/breakfast6.jpg", recipeType: RecipeType[0] },
    { id: 7, title: "Lunch nr 1", servings: 2, time: 15, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "../../assets/lunch1.jpg", recipeType: RecipeType[1] },
    { id: 8, title: "Lunch nr 2", servings: 2, time: 10, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "../../assets/lunch1.jpg", recipeType: RecipeType[1] },
    { id: 9, title: "Lunch nr 3", servings: 2, time: 30, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "../../assets/lunch1.jpg", recipeType: RecipeType[1] },
    { id: 10, title: "Lunch nr 4", servings: 2, time: 15, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "../../assets/lunch1.jpg", recipeType: RecipeType[1] },
    { id: 11, title: "Lunch nr 5", servings: 2, time: 15, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "../../assets/lunch1.jpg", recipeType: RecipeType[1] },
    { id: 12, title: "Lunch nr 6", servings: 2, time: 20, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "../../assets/lunch1.jpg", recipeType: RecipeType[1] },
    { id: 13, title: "Salad nr 1", servings: 2, time: 15, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "some picture", recipeType: RecipeType[2] },
    { id: 14, title: "Salad nr 2", servings: 2, time: 10, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "some picture", recipeType: RecipeType[2] },
    { id: 15, title: "Salad nr 3", servings: 2, time: 30, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "some picture", recipeType: RecipeType[2] },
    { id: 16, title: "Salad nr 4", servings: 2, time: 15, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "some picture", recipeType: RecipeType[2] },
    { id: 17, title: "Salad nr 5", servings: 2, time: 15, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "some picture", recipeType: RecipeType[2] },
    { id: 18, title: "Salad nr 6", servings: 2, time: 20, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "some picture", recipeType: RecipeType[2] },
    { id: 19, title: "Dinner nr 1", servings: 2, time: 15, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "some picture", recipeType: RecipeType[3] },
    { id: 20, title: "Dinner nr 2", servings: 2, time: 10, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "some picture", recipeType: RecipeType[3] },
    { id: 21, title: "Dinner nr 3", servings: 2, time: 30, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "some picture", recipeType: RecipeType[3] },
    { id: 22, title: "Dinner nr 4", servings: 2, time: 15, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "some picture", recipeType: RecipeType[3] },
    { id: 23, title: "Dinner nr 5", servings: 2, time: 15, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "some picture", recipeType: RecipeType[3] },
    { id: 24, title: "Dinner nr 6", servings: 2, time: 20, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "some picture", recipeType: RecipeType[3] },
    { id: 25, title: "Dessert nr 1", servings: 2, time: 15, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "some picture", recipeType: RecipeType[4] },
    { id: 26, title: "Dessert nr 2", servings: 2, time: 10, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "some picture", recipeType: RecipeType[4] },
    { id: 27, title: "Dessert nr 3", servings: 2, time: 30, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "some picture", recipeType: RecipeType[4] },
    { id: 28, title: "Dessert nr 4", servings: 2, time: 15, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "some picture", recipeType: RecipeType[4] },
    { id: 29, title: "Dessert nr 5", servings: 2, time: 15, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "some picture", recipeType: RecipeType[4] },
    { id: 30, title: "Dessert nr 6", servings: 2, time: 20, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "some picture", recipeType: RecipeType[4] },
    { id: 31, title: "Drink nr 1", servings: 2, time: 15, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "some picture", recipeType: RecipeType[5] },
    { id: 32, title: "Drink nr 2", servings: 2, time: 10, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "some picture", recipeType: RecipeType[5] },
    { id: 33, title: "Drink nr 3", servings: 2, time: 30, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "some picture", recipeType: RecipeType[5] },
    { id: 34, title: "Drink nr 4", servings: 2, time: 15, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "some picture", recipeType: RecipeType[5] },
    { id: 35, title: "Drink nr 5", servings: 2, time: 15, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "some picture", recipeType: RecipeType[5] },
    { id: 36, title: "Drink nr 6", servings: 2, time: 20, ingridients: ["ingridient 1", "ingridient 2", "ingridient 3"], method: "Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins. Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.", pic: "some picture", recipeType: RecipeType[5] },
  ]

  constructor(
    private _activatedRoute: ActivatedRoute,
    private _router: Router
    ) { }

  ngOnInit() {
    this.folder = this._activatedRoute.snapshot.paramMap.get('id');

  }




}
